version: '3.1'

services:
  joomla:
    image: joomla
    restart: always
    depends_on:
      - joomladb
    links:
      - joomladb
    ports:
      - 8004:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomlapass
      
  joomladb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomlapass
